apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: td8z858ce-java-springboot 
  janus-idp.io/tekton: td8z858ce-java-springboot
  backstage.io/kubernetes-id: td8z858ce-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: td8z858ce-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml